### ISSUE TITLE
Request for `split()` method on `HashMap`

### ISSUE THREAD

**Issue by rsdy** [wvwwvwwv/scalable-concurrent-containers#107]
It is a very common use-case for us in [`bloop`](https://github.com/bloopai/bloop) to use a parallel process to create a `scc::HashMap`, then split that hashmap based on various properties. Currently I do this:

```
        let mut keys = vec![];
        self.cache
            .scan_async(|k, v| {
                if v.fresh {
                    keys.push(k.clone())
                }
            })
            .await;

        let to_upsert = vec![];
        for k in keys {
            to_upsert.push(self.cache.remove_async(&k).await);
        }
...
```

It would be great if I had a native way to help do this.

**Comment by wvwwvwwv** [comment]
It looks like something like `HashMap::consume_async<F: FnMut(K, V) -> Option<(K, V)>>` or `OccupiedEntry::remove_next() -> V` should be implemented.

I'll implement something in a couple of weeks!

**Comment by wvwwvwwv** [comment]
Hi, implemented `prune` and `prune_async`.

So, the usage would be,

```rust
let mut to_upsert = vec![];
self.cache.prune_async(|_, v| {
    if v.fresh {
        to_upsert.push(v);
        None
    } else {
        Some(v)
    }
}).await;
```

=> v1.8.2 (to be published soon).
