### ISSUE TITLE
AsyncWait runs into unreachable state

### ISSUE THREAD

**Issue by sammyne** [wvwwvwwv/scalable-concurrent-containers#118]
# Environment
- Architecture: AMD64
- scc - 2.0.5
- tokio - 1.29.1

# Data structure
- `HashMap`

# Error log
```bash
thread 'tokio-runtime-worker' panicked at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/scc-2.0.5/src/wait_queue.rs:178:13:
internal error: entered unreachable code
```

**Comment by wvwwvwwv** [comment]
Hello @sammyne

Thanks for reporting this issue. In order for me to understand the problem, can you possibly provide additional information?
1. Data structure used in the scenario: e.g., TreeIndex? or HashMap?
2. Architecture: e.g., AMD64? AARCH64?

**Comment by sammyne** [comment]
> Hello @sammyne
> 
> Thanks for reporting this issue. In order for me to understand the problem, can you possibly provide additional information?
> 
> 1. Data structure used in the scenario: e.g., TreeIndex? or HashMap?
> 2. Architecture: e.g., AMD64? AARCH64?

It's HashMap in use, and architecture is AMD64.

**Comment by wvwwvwwv** [comment]
Thanks! It seems to me that a Future was dropped without having been awaited. I’ll look into it!

**Comment by wvwwvwwv** [comment]
Confirm that the problem is reproducible if `AsyncAwait` is dropped without being awaited.

**Comment by sammyne** [comment]
> Confirm that the problem is reproducible if `AsyncAwait` is dropped without being awaited.

Is it possible to support potentially non-awaited `AsyncAwait`? 

This would help for case like put HashMap's op in `tokio::select!` which may never await HashMap's op.

**Comment by wvwwvwwv** [comment]
@sammyne Sure, that's exactly what I'm trying to fix! I'll need to upload a few changes, and hopefully, I'll be able to upload SCC 2.0.6 by tomorrow.

**Comment by sammyne** [comment]
> @sammyne Sure, that's exactly what I'm trying to fix! I'll need to upload a few changes, and hopefully, I'll be able to upload SCC 2.0.6 by tomorrow.

Great thanks 😄  Waiting for 2.0.6.

**Comment by wvwwvwwv** [comment]
Uploaded 2.0.6! Reopen this when it does not work :-)
