### ISSUE TITLE
[FEATURE REQUEST] expose API for getting bucket index of HashMap key to help debug contention

### ISSUE THREAD

**Issue by sammyne** [wvwwvwwv/scalable-concurrent-containers#119]
It can be exposed on an added feature, like `dev`. So that normaly user won't see it.

**Comment by wvwwvwwv** [comment]
Looks like a great idea, and I guess the method can also be public.
- I'll add respective public methods in ~1 week.

**Comment by wvwwvwwv** [comment]
`bucket_index` is available in 2.0.7!
