### ISSUE TITLE
len() for Queue, Stack, Bag

### ISSUE THREAD

**Issue by beckend** [wvwwvwwv/scalable-concurrent-containers#125]
Possible to request to get a hint on the length of these?

**Comment by wvwwvwwv** [comment]
Yes, absolutely possible, but unfortunately, the time complexity will be O(N) since there is no dedicated field for tracking the count of entries. I'll implement `len` methods for those data structures.

**Comment by wvwwvwwv** [comment]
Uploaded SCC 2.0.13 just now!

**Comment by beckend** [comment]
Thanks!
