### ISSUE TITLE
Premature evicting entries in HashCache

### ISSUE THREAD

**Issue by feymartynov** [wvwwvwwv/scalable-concurrent-containers#130]
The following example often panics proving that HashCache may evict entries even when capacity is not yet fully occupated.

```rust
const CAPACITY: usize = 64;
let hc = scc::HashCache::with_capacity(CAPACITY, CAPACITY);

for i in 0..CAPACITY {
    let k = format!("key{i}");

    match hc.put(k, i).unwrap() {
        None => (),
        Some((k, _)) => panic!("Evicted {k}"),
    }
}
```

Is this a bug or normal behavior?
If it's normal, I think it should be documented.

**Comment by wvwwvwwv** [comment]
Hi!

It’s unfortunately intended. HashCache is basically the same with HashMap except that it evicts an entry if the bucket is full instead of allocating backup linked list storage, even when there are free slots in other buckets. I’ll add this to the document!

**Comment by wvwwvwwv** [comment]
Updated the doc!
