### ISSUE TITLE
Remove unnecessary trait bounds on container types

### ISSUE THREAD

**Issue by JieningYu** [wvwwvwwv/scalable-concurrent-containers#135]
For example, [`HashMap`](https://docs.rs/scc/latest/scc/hash_map/struct.HashMap.html)s have unnecessary trait bounds on type definition (`where K: Hash + Eq`), and these could make types using `scc` containers inherent these unnecessary bounds.

**Comment by wvwwvwwv** [comment]
I agree, I’ll remove those bounds in the upcoming release: hopefully in 2 weeks.

**Comment by wvwwvwwv** [comment]
Uploaded a fix; it is not complete since K, V: 'static is remaining in HashIndex, and TreeIndex is not addressed.
