### ISSUE TITLE
Example question

### ISSUE THREAD

**Issue by NathanielPrescott** [wvwwvwwv/scalable-concurrent-containers#137]
Hello,

I was just wondering if you knew about any other projects that are utilizing the different containers / utilities you've built here?  I was looking for some examples of things like the HashMap, HashIndex, and HashCache in action.

Thanks,
Nathan

**Comment by novacrazy** [comment]
I use `scc` extensively within the [Lantern Chat](https://github.com/search?q=scc%3A%3A+repo%3ALantern-chat%2Fserver+&type=code) project. Been following `scc` for years and it's really quality. The lock-free `peek` method on `HashIndex` is especially awesome. Even `TreeIndex` is used in my code.

Have not used `HashCache` yet despite actually being the one to request an LRU-like map, so oops. What was implemented ended up not being exactly appropriate for my use cases. However, I'm definitely looking for places where I can use it. 

There's nothing else out there like `scc` and it's pretty much my go-to for concurrent structures. There have been multiple times where I've considered something like `sled` or `rocksdb` for in-memory stuff but then realized, "Oh, `scc` can do that way simpler and probably faster, plus async if needed."

**Comment by NathanielPrescott** [comment]
Sounds good, thank you both for responding!
