### ISSUE TITLE
request: Adopt equivalent::Equivalent and equivalent::Comparable

### ISSUE THREAD

**Issue by qthree** [wvwwvwwv/scalable-concurrent-containers#162]
hashbrown crate uses [Equivalent](https://docs.rs/hashbrown/latest/hashbrown/trait.Equivalent.html) trait instead of Borrow for get operations. It's much more useful cause you can't return non-reference from Borrow::borrow, for example if you want to implement you own String/str combination (newtypes).
Of course you can use bytemuck transparent derive to convert between &str and newtype reference, but that's not ideal, for example if want to add another field into query type.
I propose to rewrite all scc methods to use new Equivalent trait instead of Borrow, and do blanket impl for Borrow as hashbrown does.

**Comment by qthree** [comment]
And for TreeIndex we can add another trait for Borrow + Ord, something like
```rust
pub trait Compare<K: ?Sized> {
    // Required method
    fn compare(&self, key: &K) -> std::cmp::Ordering;
}

impl<Q, K> Compare<K> for Q
where
    Q: Ord + ?Sized,
    K: Borrow<Q> + ?Sized,
{
    fn compare(&self, key: &K) -> std::cmp::Ordering {
        self.cmp(key.borrow())
    }
}
```

**Comment by qthree** [comment]
Actually, there is already [crate](https://docs.rs/equivalent/latest/equivalent/) with exactly those two traits, what's your policy for adding deps?

**Comment by wvwwvwwv** [comment]
Hi @qthree,

This looks a really good idea, thanks a lot. On the other hand, the crate seems way too trivial to be a dependency, so can you possibly use your own code in your comment (in compare.rs? + for the equivalent trait, you may have to state that the code is "inspired" or "copied" from the equivalent crate) instead of adding the crate to Cargo.toml?

**Comment by qthree** [comment]
@wvwwvwwv I can do It [the same way hashbrown did it.](https://github.com/rust-lang/hashbrown/blob/a25cd3b715fb6c15841cc7cc7777eda56e0bce8b/src/lib.rs#L130)
Copy-paste Comparable and Equivalent traits into scc, in a new module, but then place this new module under `#[cfg(not(feature = "equivalent")].
So if users want to they can enable equivalent dependency. For example if they want to use the same query type [in different maps](https://github.com/indexmap-rs/indexmap/blob/d74a4daffbfffba72c1e07fcb5c45a449c5b36e1/Cargo.toml#L17) without reimplementing the same trait twice.

**Comment by wvwwvwwv** [comment]
TODO: do the same for Hash*.

**Comment by wvwwvwwv** [comment]
=> SCC 2.2.0
