### ISSUE TITLE
`HashMap::get` get old value which has been overrided by `HashMap::insert` operation.

### ISSUE THREAD

**Issue by louis-she** [wvwwvwwv/scalable-concurrent-containers#165]
First of all thanks for the great project,

I am developing a reverse proxy and using `scc::HashMap` to save all the rules (hostname as key, and upstream ip + upstream port as value), there are millions of it.

I found that when i override some existing key by `HashMap::insert`, the `HashMap::get` **WILL NOT** get the latest value, but the previous value which should have been overrided.

The rules object is created as a global static variable like bellow:

```rust
lazy_static! {
    pub static ref RULES: scc::HashMap<String, Arc<Upstream>> = scc::HashMap::new();
}
```

and my project is based on tokio,

Any ideas?

**Comment by wvwwvwwv** [comment]
Hi! The semantics of scc::HashMap::insert differs from that of std::collections::HashMap::insert - it does not replace the old value. If you need similar semantics, please try scc::HashMap::upsert.

**Comment by louis-she** [comment]
thanks! `upsert` is what i want, have to upgrade the crate to newest version though : )
