### ISSUE TITLE
[Question] Question about locking

### ISSUE THREAD

**Issue by CR7273868** [wvwwvwwv/scalable-concurrent-containers#170]
------------ a piece from github repo of SCC
HashMap
[HashMap](https://github.com/wvwwvwwv/scalable-concurrent-containers#hashmap) is a concurrent hash map, optimized for highly parallel write-heavy workloads. [HashMap](https://github.com/wvwwvwwv/scalable-concurrent-containers#hashmap) is structured as a lock-free stack of entry bucket arrays. The entry bucket array is managed by [sdd](https://crates.io/crates/sdd), thus enabling lock-free access to it and non-blocking container resizing. Each bucket is a fixed-size array of entries, and it is protected by a special read-write lock which provides both blocking and asynchronous methods.

Locking behavior
Entry access: fine-grained locking
Read/write access to an entry is serialized by the read-write lock in the bucket containing the entry. There are no container-level locks, therefore, the larger the container gets, the lower the chance of the bucket-level lock being contended.
------------- END of github repo piece

I read this from the github repo of SCC Hashmap.

I have a project where I have multiple websocket connections (bots) reading commands and modifying their state. SCC will be the backend aka shared state cache hashmap in Arc<State> struct which allows modifying it outside of their respective websocket tasks.

How is the Locking behavior of SCC different as let's say DashMAP. I heard DashMAP can deadlock more often if there is another reference of that item ? 

Take this from their docs.rs for example (docs.rs of dashmap):

pub fn [insert](https://docs.rs/dashmap/latest/dashmap/struct.DashMap.html#method.insert)(&self, key: K, value: V) -> [Option](https://doc.rust-lang.org/nightly/core/option/enum.Option.html)<V>

Inserts a key and a value into the map. Returns the old value associated with the key if there was one.

Locking behaviour: May deadlock if called when holding any sort of reference into the map.

I understand dashmap shards to the amount of cores or threads a system has. and that holding any reference of a shard / map can cause it to deadlock?

My follow-up question is does scc suffer from this? How does it approach locking?

What are buckets ? I understand the container is the entire hashmap itself. 

I am trying to come up with a best case scenario for my new V3 project. Thanks for your time!

Might a HashIndex or TreeIndex fit my better use case? As the entry value is Arc<T>.

Everything inside the entry value (Arc<T>) is modified either using atomics or an uncontended RWLOCK / Mutex. Which would make HashIndex perfect as I would not need &mut references to my struct type.

What would you pick and why? There is a lot of other pieces of code accessing the map. But everything resides in an Arc. And inner values are modified thru Atomics or uncontended locks.

I did read: Linearizability, read operations are not linearizable. (HashIndex)

This has most likely something to do with atomics. As latest writes are not always visible by writers in a specific atomic order I assume? Would this have any cost for my use case? Writes to map are very infrequent if not somehow rare.

**Comment by wvwwvwwv** [comment]
> How is the Locking behavior of SCC different as let's say DashMAP. I heard DashMAP can deadlock more often if there is another reference of that item ?

The locking behavior is not substantially different from that of the dashmap; the only significant difference is the number of locks: SCC = dynamically growing/shrinking (this makes the data structure super "scalable") vs. dashmap = fixed.

> I understand dashmap shards to the amount of cores or threads a system has. and that holding any reference of a shard / map can cause it to deadlock?

Not necessarily. More precisely, a thread referencing a shard/entry attempting to "additionally" hold another reference to a shard/entry may lead to a deadlock.

> My follow-up question is does scc suffer from this? How does it approach locking?

Again, the locking behavior itself is similar. However, SCC provides asynchronous methods, which are super helpful when only a limited number of executors are available in the system.

> What are buckets ? I understand the container is the entire hashmap itself.

Buckets are the locking unit. Each bucket contains 32 entry slots and shares the same RW lock.

> Everything inside the entry value (Arc) is modified using atomics or an uncontended RWLOCK / Mutex. Which would make HashIndex perfect as I would not need &mut references to my struct type.

If you never need `&mut V` and expect read-heavy workloads, HashIndex will perform better. If ordering matters, TreeIndex will be the best choice.

> This has most likely something to do with atomics. As latest writes are not always visible by writers in a specific atomic order I assume? Would this have any cost for my use case? Writes to map are very infrequent if they are rare.

In most mainstream architectures including x86/AARCH64, data freshness is guaranteed by the cache coherency layer after an RMW operation; therefore, there should be no anomalies. It just means that the C++ memory model does not explicitly define data freshness, and there is a 'possibility' of a hardware architecture implemented very differently.
-> In short, don't worry.
