### ISSUE TITLE
[Feature]: Range-based iterator for TreeIndex

### ISSUE THREAD

**Issue by novacrazy** [wvwwvwwv/scalable-concurrent-containers#33]
Would be great to have something similar to https://doc.rust-lang.org/std/collections/struct.BTreeMap.html#method.range

**Comment by wvwwvwwv** [comment]
Agreed. I'll implement TreeIndex::range(&self, range) soon.

**Comment by wvwwvwwv** [comment]
API change.

TreeIndex::from(&self, key: &K) -> Scanner<_, K, V>
will be replaced with
TreeIndex::range<R: RangeBounds<K>>(&self, range: R) -> Range<_, K, V, R>

DoubleEndedIterator is not going to be implemented this time as the data structure does not reliably manage backward links of leaf nodes.

**Comment by wvwwvwwv** [comment]
fixed: 0.4.9
