### ISSUE TITLE
Implement conditional removal

### ISSUE THREAD

**Issue by estaban** [wvwwvwwv/scalable-concurrent-containers#44]
Implement removal of a key if a predicate on the existing value is met.

```
pub fn remove_if(
    &self,
    key: &K,
    f: impl FnOnce(&K, &V) -> bool
) -> Option<V>
```

**Comment by wvwwvwwv** [comment]
Great idea. There are lots to enhance in the data structure including some lifetime issues, but I haven't had time to address them for the past few months. I'll implement the API when I'm free (in Aug?).

**Comment by wvwwvwwv** [comment]
I'm on it right now. It requires some time because I found serious issues in `HashMap` here and there, and it needs a complete overhaul, including the API.
