### ISSUE TITLE
Implement retain on HashIndex?

### ISSUE THREAD

**Issue by novacrazy** [wvwwvwwv/scalable-concurrent-containers#93]
Would it be possible to implement `retain`/`retain_async` on `HashIndex`? 

Otherwise I'll have to use `HashMap` or iterate and create a list of keys to remove.

**Comment by wvwwvwwv** [comment]
Definitely possible. I'll implement them (+ any/any_async) next week.

In the meantime, you can try following if your code allows blocking code:

```rust
// No locks are acquired during iteration over entries, however `HashIndex` iterators cannot be sent across `awaits`.
hashindex.iter(&barrier).for_each(|(k, v)| {
    if !retain_cond(k, v) {
        // IT IS A BLOCKIG METHOD; the corresponding bucket will be locked during entry removal.
        hashindex.remove(k);
   }
}
```

**Comment by wvwwvwwv** [comment]
Well, easier than I thought, though some code is repeated here and there (later, need to refactor the code once `async_fn_in_trait` gets stabilized. I'll upload 1.6.2 in an hour.

**Comment by novacrazy** [comment]
Phenomenal response time! Hopefully I can get scc up and running in my server today.

**Comment by wvwwvwwv** [comment]
Done (v1.6.2)! Hope that the new methods work as expected.
